version: "3.9"

services:
  app:
    image: devfull/app:latest
    ports:
      - "8080:8080"

#  db:
#    image: devfull/db
#    volumes:
#      - pg-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
#    networks:
#      - twwo
#    environment:
#      PGDATA: /var/lib/postgresql/data/pgdata
#      POSTGRES_PASSWORD: Secret123!
#      TWWO_USERNAME: twwo
#      TWWO_PASSWORD: twwo
#      TWWO_DATABASE: twwo

volumes:
  pg-data:

networks:
  twwo:
